spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.224.41.157:3306/team01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  mvc:
    date-format: yyyy-MM-dd

  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8

pagehelper:
                    helper-dialect: mysql
                    reasonable: true
                    support-methods-arguments: true
                    params: count==countSql
                    page-size-zero: true



